version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017" 
  mongo-seed:
    build: ./data
    links:
      - mongo
  app:
    container_name: "apps"
    build: "./app"
    ports:
      - "3005:3005"
    restart: unless-stopped
    depends_on:
      - mongo